### ISSUE TITLE
Faiils to Install

### ISSUE THREAD

**Issue by snvv** [lucasgodeiro/TextForecast#1]
Hello
When I try to install TextForecast both in windows and linux, it fails with the following error:

** byte-compile and prepare package for lazy loading
Error in namespaceExport(ns, exports) : 
  undefined exports: pdf_combine, pdf_compress, pdf_length, pdf_split, pdf_subset
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace -> namespaceExport
Execution halted
ERROR: lazy loading failed for package ‘TextForecast’
* removing ‘/home/snvv/R/x86_64-pc-linux-gnu-library/3.6/TextForecast’
Warning in install.packages :
  installation of package ‘TextForecast’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpdcwJrB/downloaded_packages’
```
Is something that I can do?
Thank you
SN

**Comment by lucasgodeiro** [comment]
Hi, Could you try to install using GitHub? 

install.packages("devtools")
library(devtools)
install_github("lucasgodeiro/TextForecast")

**Comment by snvv** [comment]
Hi,
Ι have tried but nothing has changed. I get the same errors.

**Comment by lucasgodeiro** [comment]
Hi, Try to install the package “qpdf” first. 
These function are from this package. 
https://www.rdocumentation.org/packages/qpdf/versions/1.1/topics/qpdf

**Comment by snvv** [comment]
OK. qpdf was the problem.
Thank you very much.
